name: google_gemini
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_generative_ai: ^0.2.1
  hive: ^2.2.3
  path_provider: ^2.1.2
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  speech_to_text: ^6.6.1
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - .env